---
title: "Simple XGBoost"
output: html_notebook
---

```{r, include=F}
library(tidyverse)
library(DALEX)
library(ggplot2)
library(GGally)
library(ggthemes)
library(gridExtra)
library(caret)
library(glmnet)

source('../data_utils.R')
```

```{r}
data = read_modelling('../data', target_col = 'recid_violent')
data = split_data(data)

data$train %>% head()
```

```{r}
set.seed(42)
folds = caret::groupKFold(data$train$person_id, k = 5)
folds_test = lapply(folds, function(x) (1:nrow(data$train))[-x])

xlevs_train = data$train %>% select(-recid_violent)
xlevs <- lapply(xlevs_train[, sapply(data$train %>% select(-recid_violent), is.factor), drop = F], function(j){
    levels(j)
})
```

```{r}
dtrain = model.matrix(recid_violent ~ . - person_id - 1, 
                      data = data$train)
foldid = rep(-1, nrow(dtrain))
for (i in 1:length(folds_test)) {
    foldid[folds_test[[i]]] = i
}

cv_glmnet_violent = cv.glmnet(dtrain, data$train$recid_violent  == 1, family = 'binomial', foldid = foldid,
                      type.measure = 'deviance', keep = TRUE)
plot(cv_glmnet_violent)
```

```{r}
glmnet_predict_violent = function(model, data) {
    data = model.matrix(recid_violent ~ . - person_id - 1, data = data, xlev = xlevs)
    predict(model, data, type = 'response', s = 'lambda.min')[, 1]
}

cv_glmnet_explain_violent = DALEX::explain(cv_glmnet_violent, data = data$test,
                                    y = data$test$recid_violent == 1, 
                                    type = 'classification', label = 'Lasso CV Violent',
                                    predict_function = glmnet_predict)
```

```{r}
glmnet_perf_violent = DALEX::model_performance(cv_glmnet_explain_violent, cutoff = 0.16)
glmnet_perf_violent
```

```{r}
save(cv_glmnet_explain_violent, cv_glmnet_violent, file = 'lasso_all_violent.RData')
```

