# -*- coding: utf-8 -*-
"""PDP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qnzmnrnwI-rMO_SfPUXN3nW9BchYadmH
"""

from profiles import train, X_train, Y_train, X_valid, Y_valid, column_names, treatment_col
from model import train_xgb_model, train_logistic, evaluate_uplift, simple_network, check_acc_diff, check_uplift_diff, local_search_xgb, calc_uplift, predict_treatment
import pandas as pd
#from pycebox.ice import ice, ice_plot
import matplotlib.pyplot as plt
import dalex
import xgboost as xg
import numpy as np

r_xgb_model = local_search_xgb(X_train, Y_train, X_valid, Y_valid, treatment_col, just_get_model=True)

def calc_uplift_filled(model, x):
    treatment_col=11
    #x = np.array(x)
    return predict_treatment(model, treatment_col, 1)(np.array(x)) - predict_treatment(model, treatment_col, 0)(np.array(x))

exp = dalex.Explainer(r_xgb_model, X_train,Y_train, label = "xgboost", predict_function = calc_uplift_filled)

exp.model_profile(type='partial')

#forty_ice_df = ice(data=train_X_imp_df[:5000], column='history', 
#                   predict = lambda X: calc_uplift(r_xgb_model, X,treatment_col))
#ice_plot(forty_ice_df, c='dimgray', linewidth=0.3)
#plt.ylabel('Pred. AV %ile')
#plt.xlabel('history');
#ice_plot(forty_ice_df, linewidth=.5, plot_pdp=True, 
#         pdp_kwargs={'c': 'k', 'linewidth': 3})
#plt.ylabel('Pred. AV %ile')
#plt.xlabel('history');
