observation = [
  {
    "ExternalRiskEstimate": 40,
    "MSinceOldestTradeOpen": 177,
    "MSinceMostRecentTradeOpen": 1,
    "AverageMInFile": 64,
    "NumSatisfactoryTrades": 4,
    "NumTrades60Ever2DerogPubRec": 14,
    "PercentTradesNeverDelq": 29,
    "MSinceMostRecentDelq": 2,
    "MaxDelq2PublicRecLast12M": 0,
    "MaxDelqEver": 2,
    "NumTotalTrades": 17,
    "PercentInstallTrades": 53,
    "MSinceMostRecentInqexcl7days": -7,
    "NumInqLast6M": 8,
    "NumInqLast6Mexcl7days": 8,
    "NetFractionRevolvingBurden": 106,
    "NetFractionInstallBurden": 97,
    "NumRevolvingTradesWBalance": 1,
    "PercentTradesWBalance": 100,
    "_yhat_": 0.0006645044098758153,
    "_label_": "TruePositive",
    "_ids_": 0,
    "_y_": "Bad"
  },
  {
    "ExternalRiskEstimate": 89,
    "MSinceOldestTradeOpen": 521,
    "MSinceMostRecentTradeOpen": 15,
    "AverageMInFile": 244,
    "NumSatisfactoryTrades": 27,
    "NumTrades60Ever2DerogPubRec": 0,
    "PercentTradesNeverDelq": 100,
    "MSinceMostRecentDelq": -7,
    "MaxDelq2PublicRecLast12M": 7,
    "MaxDelqEver": 8,
    "NumTotalTrades": 30,
    "PercentInstallTrades": 19,
    "MSinceMostRecentInqexcl7days": -8,
    "NumInqLast6M": 0,
    "NumInqLast6Mexcl7days": 0,
    "NetFractionRevolvingBurden": 3,
    "NetFractionInstallBurden": -8,
    "NumRevolvingTradesWBalance": 3,
    "PercentTradesWBalance": 33,
    "_yhat_": 0.9598542356740429,
    "_label_": "FalsePositive",
    "_ids_": 0,
    "_y_": "Good"
  },
  {
    "ExternalRiskEstimate": 58,
    "MSinceOldestTradeOpen": 14,
    "MSinceMostRecentTradeOpen": 1,
    "AverageMInFile": 6,
    "NumSatisfactoryTrades": 3,
    "NumTrades60Ever2DerogPubRec": 0,
    "PercentTradesNeverDelq": 100,
    "MSinceMostRecentDelq": -7,
    "MaxDelq2PublicRecLast12M": 7,
    "MaxDelqEver": 8,
    "NumTotalTrades": 5,
    "PercentInstallTrades": 40,
    "MSinceMostRecentInqexcl7days": -7,
    "NumInqLast6M": 15,
    "NumInqLast6Mexcl7days": 15,
    "NetFractionRevolvingBurden": 98,
    "NetFractionInstallBurden": -8,
    "NumRevolvingTradesWBalance": 2,
    "PercentTradesWBalance": 80,
    "_yhat_": 0.013079915804227961,
    "_label_": "TrueNegative",
    "_ids_": 0,
    "_y_": "Good"
  },
  {
    "ExternalRiskEstimate": 91,
    "MSinceOldestTradeOpen": 494,
    "MSinceMostRecentTradeOpen": 6,
    "AverageMInFile": 173,
    "NumSatisfactoryTrades": 15,
    "NumTrades60Ever2DerogPubRec": 0,
    "PercentTradesNeverDelq": 100,
    "MSinceMostRecentDelq": -7,
    "MaxDelq2PublicRecLast12M": 7,
    "MaxDelqEver": 8,
    "NumTotalTrades": 15,
    "PercentInstallTrades": 0,
    "MSinceMostRecentInqexcl7days": 0,
    "NumInqLast6M": 0,
    "NumInqLast6Mexcl7days": 0,
    "NetFractionRevolvingBurden": 1,
    "NetFractionInstallBurden": -8,
    "NumRevolvingTradesWBalance": 2,
    "PercentTradesWBalance": 29,
    "_yhat_": 0.9515411753179782,
    "_label_": "FalseNegative",
    "_ids_": 0,
    "_y_": "Bad"
  }
];