observation = [
  {
    "ExternalRiskEstimate": 91,
    "MSinceOldestTradeOpen": 494,
    "MSinceMostRecentTradeOpen": 6,
    "AverageMInFile": 173,
    "NumSatisfactoryTrades": 15,
    "NumTrades60Ever2DerogPubRec": 0,
    "PercentTradesNeverDelq": 100,
    "MSinceMostRecentDelq": -7,
    "MaxDelq2PublicRecLast12M": 7,
    "MaxDelqEver": 8,
    "NumTotalTrades": 15,
    "PercentInstallTrades": 0,
    "MSinceMostRecentInqexcl7days": 0,
    "NumInqLast6M": 0,
    "NumInqLast6Mexcl7days": 0,
    "NetFractionRevolvingBurden": 1,
    "NetFractionInstallBurden": -8,
    "NumRevolvingTradesWBalance": 2,
    "PercentTradesWBalance": 29,
    "_yhat_": 0.9515411753179782,
    "_label_": "linear",
    "_ids_": 0,
    "_y_": "Bad"
  },
  {
    "ExternalRiskEstimate": 91,
    "MSinceOldestTradeOpen": 494,
    "MSinceMostRecentTradeOpen": 6,
    "AverageMInFile": 173,
    "NumSatisfactoryTrades": 15,
    "NumTrades60Ever2DerogPubRec": 0,
    "PercentTradesNeverDelq": 100,
    "MSinceMostRecentDelq": -7,
    "MaxDelq2PublicRecLast12M": 7,
    "MaxDelqEver": 8,
    "NumTotalTrades": 15,
    "PercentInstallTrades": 0,
    "MSinceMostRecentInqexcl7days": 0,
    "NumInqLast6M": 0,
    "NumInqLast6Mexcl7days": 0,
    "NetFractionRevolvingBurden": 1,
    "NetFractionInstallBurden": -8,
    "NumRevolvingTradesWBalance": 2,
    "PercentTradesWBalance": 29,
    "_yhat_": 0.9385550305680795,
    "_label_": "NeuralNet",
    "_ids_": 0,
    "_y_": "Bad"
  }
];